### ISSUE TITLE
Traceback at the end of the program

### ISSUE THREAD

**Issue by Phyks** [Phyks/Blissify#5]
``` python
Done! :)
Traceback (most recent call last):
  File "server.py", line 183, in <module>
    full_rescan(args.mpd_root)
  File "server.py", line 98, in full_rescan
    last_modified = client.find("file", song)["last_modified"]
  File "/usr/lib/python3.5/site-packages/mpd.py", line 629, in decorator
    return wrapper(self, name, args, bound_decorator(self, returnValue))
  File "/usr/lib/python3.5/site-packages/mpd.py", line 254, in _execute
    return retval()
  File "/usr/lib/python3.5/site-packages/mpd.py", line 623, in decorator
    return function(self, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/mpd.py", line 422, in _fetch_songs
    return self._fetch_objects(["file"])
  File "/usr/lib/python3.5/site-packages/mpd.py", line 410, in _fetch_objects
    return self._wrap_iterator(self._read_objects(delimiters))
  File "/usr/lib/python3.5/site-packages/mpd.py", line 374, in _wrap_iterator
    return list(iterator)
  File "/usr/lib/python3.5/site-packages/mpd.py", line 332, in _read_objects
    for key, value in self._read_pairs():
  File "/usr/lib/python3.5/site-packages/mpd.py", line 311, in _read_pairs
    pair = self._read_pair(separator)
  File "/usr/lib/python3.5/site-packages/mpd.py", line 302, in _read_pair
    line = self._read_line()
  File "/usr/lib/python3.5/site-packages/mpd.py", line 287, in _read_line
    raise ConnectionError("Connection lost while reading line")
mpd.ConnectionError: Connection lost while reading line
```

**Comment by Phyks** [comment]
Fixed by https://github.com/Phyks/Blissify/pull/12.

**Comment by Phyks** [comment]
Fixed by https://github.com/Phyks/Blissify/pull/12.
